#include <list>
using namespace std;
void Menu();
bool Input(list<int>&, const char[]);
void Output(list<int>&);
void DeleteElements(list<int>&);
void AddElements(list<int>&);
void FindGreater(list<int>&);
void SearchPair(list<int>&);
void Divide(list<int>&);
void MultiplyLists(list<int>&);
void Sum(list<int>&);
void ChangeSign(list<int>&);
void FindSorted(list<int>&);
void MultiplyElements(list<int>&);
void FillRandom(list<int>&);
void DivideInTwo(list<int>&);
void FindSquare(list<int>&);
void AddX(list<int>&);
void RemoveIf(list<int>&);
void CountIf(list<int>&);
void FindSquareSum(list<int>&);
void RemoveIf2(list<int>&);
void Permutations(list<int>&);